apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::827795719134:role/eksctl-eksctl-demo-nodegroup-ng-9-NodeInstanceRole-WFY4DVYTPC3F
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::827795719134:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-07-23T14:29:45Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1591"
  uid: bb8c4564-e288-44f4-b3bf-c53c95d1cdfc
